---
title: "Data Visualization with R"
subtitle: "This is my personal catalog of chart and how to make it in R"
author: "Panggah D. Putra"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
    toc_depth: 2
    number_sections: true
    theme: lumen
    highlight: tango
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```

***

# Prerequisites

## Load packages

```{r, message=FALSE}

library (tidyverse)
library (ggbump) # to make a bump chart
library(ggdist) # to make a dot plot
library(ggbeeswarm) # to make a beeswarm plot
library(ggalt) # to make a dot plot (dumbbell plot)
library(CGPfunctions) # to make a slope graph

```

## Prepare datasets

```{r main df}

set.seed(2000)
df1 = tibble(var = 'A', val = rnorm(n = 25, mean = 5.5, sd = 1.5))
df2 = tibble(var = 'B', val = rnorm(n = 15, mean = 4.5, sd = 1.0))
df3 = tibble(var = 'C', val = rnorm(n = 20, mean = 5.0, sd = 1.0))
df4 = tibble(var = 'D', val = rnorm(n = 10, mean = 4.0, sd = 0.5))
df5 = tibble(var = 'E', val = rnorm(n = 13, mean = 5.0, sd = 1.5))

main_df <- rbind(df1, df2, df3, df4, df5) %>%
  mutate(Variable = as_factor(var),
         value = round(val, 2)) %>%
  select(Variable, value)

```

```{r df for bump}

set.seed(2021)
df_6 = tibble(team = c('A','B','C','D','E'),
              game_1 = sample(1:5),
              game_2 = sample(1:5),
              game_3 = sample(1:5),
              game_4 = sample(1:5),
              game_5 = sample(1:5))

df_for_bump <- df_6 %>%
  pivot_longer(!team, names_to = 'game', values_to = 'position') %>%
  mutate(game = as.numeric(recode(game,
                                  game_1 = 1,
                                  game_2 = 2,
                                  game_3 = 3,
                                  game_4 = 4,
                                  game_5 = 5)))

```

```{r df for slope}

df_for_slope = tibble(var = c('A','B','C','D', 'E',
                              'A','B','C','D', 'E',
                              'A','B','C','D', 'E'),
                     month = c('2010','2010','2010','2010','2010',
                               '2015','2015','2015','2015','2015',
                               '2020','2020','2020','2020','2020'),
                     val = c(10,8,6,4,2,
                             13,9,11,5,7,
                             12,13,9,7,5))

```

```{r palette for ranking}

palette_ranking <- c('#134b73',
                     '#2f70a1',
                     '#4692b0',
                     '#72aeb6',
                     '#abc9c8')

```

```{r palette for distribution}

palette_distr <-c('#4e3910',
                  '#845d29',
                  '#4fb6ca',
                  '#178f92',
                  '#175f5d')

```

```{r theme for rangking}

theme_ranking <- theme_minimal() +
  theme(
    plot.title = element_text(color = '#0a3351',
                              hjust = 0.5,
                              face = 'bold'),
    plot.subtitle = element_text(color = '#0a3351',
                                 hjust = 0.5),
    plot.caption = element_text(color = '#0a3351',
                                hjust = 1),
    axis.title = element_text(color = '#0a3351',
                              face = 'bold'),
    axis.text = element_text(color = '#0a3351',
                             face = 'bold'),
    panel.background = element_rect(fill = '#f0ffff',
                                    color = NA),
    plot.background = element_rect(fill = '#f0ffff',
                                   color = 'lightblue')
  )

```

```{r theme for distribution}

theme_distr <- theme_minimal() +
  theme(
    plot.title = element_text(color = '#1d1f54',
                              hjust = 0.5,
                              face = 'bold'),
    plot.subtitle = element_text(color = '#1d1f54',
                                 hjust = 0.5),
    plot.caption = element_text(color = '#1d1f54',
                                hjust = 1),
    axis.title = element_text(color = '#1d1f54',
                              face = 'bold'),
    axis.text = element_text(color = '#1d1f54',
                             face = 'bold'),
    panel.background = element_rect(fill = '#FFFCDE',
                                    color = NA),
    plot.background = element_rect(fill = '#FFFCDE',
                                   color = 'lightblue')
  )

```

***

# Ranking

## Ordered Bar

```{r ordered bar}

ordered_bar <- main_df %>%
  group_by(Variable) %>%
  summarise(number_of_data = n()) %>%
  ggplot(aes(x = reorder(Variable, -number_of_data),
             y = number_of_data,
             color = reorder(Variable, -number_of_data),
             fill = reorder(Variable, -number_of_data))) +
  geom_col(alpha = .9, width = .6) +
  scale_color_manual(values = palette_ranking,
                     guide = 'none') +
  scale_fill_manual(values = palette_ranking,
                    guide = 'none') +
  theme_ranking +
  xlab('Variable') +
  ylab('number of data') +
  labs(title = 'Ordered Bar',
       subtitle = 'Ordered bar use to show bla bla bla.',
       caption = 'visualization by PanggahDPutra, 2022')

```

```{r ordered bar print, echo=FALSE, out.width = "100%"}
ordered_bar
```

## Ordered Column

```{r ordered column}

ordered_column <- main_df %>%
  group_by(Variable) %>%
  summarise(number_of_data = n()) %>%
  ggplot(aes(x = number_of_data,
             y = reorder(Variable, number_of_data),
             color = reorder(Variable, -number_of_data),
             fill = reorder(Variable, -number_of_data))) +
  geom_col(alpha = .9, width = .6) +
  scale_color_manual(values = palette_ranking,
                     guide = 'none') +
  scale_fill_manual(values = palette_ranking,
                    guide = 'none') +
  theme_ranking +
  xlab('number of data') +
  ylab('Variable') +
  labs(title = 'Ordered Column',
       subtitle = 'Ordered column use to show bla bla bla.',
       caption = 'visualization by PanggahDPutra, 2022')

```

```{r ordered column print, echo=FALSE, out.width = "100%"}
ordered_column
```

## Slope Graph

```{r slope graph}

slope_graph <- newggslopegraph(
  dataframe = df_for_slope,
  Times = month,
  Measurement = val,
  Grouping = var,
  Title = 'Slope Graph',
  SubTitle = 'Slope Graph use to show bla bla bla.',
  Caption = 'visualization by PanggahDPutra, 2022',
  XTextSize = 12,
  YTextSize = 4,
  TitleTextSize = 14,
  SubTitleTextSize = 10,
  CaptionTextSize = 8,
  TitleJustify = "center",
  SubTitleJustify = "center",
  CaptionJustify = "right",
  LineThickness = 1.2,
  LineColor = palette_ranking,
  DataTextSize = 5,
  DataTextColor = '#0a3351',
  DataLabelPadding = 0.1,
  DataLabelFillColor = '#f0ffff',
  WiderLabels = TRUE) +
  theme(
    plot.title = element_text(color = '#0a3351'),
    plot.subtitle = element_text(color = '#0a3351'),
    plot.caption = element_text(color = '#0a3351'),
    panel.background = element_rect(fill = '#f0ffff',
                                    color = NA),
    plot.background = element_rect(fill = '#f0ffff',
                                   color = 'lightblue')) 

```

```{r slope graph print, echo=FALSE, out.width = "100%"}
slope_graph
```

## Lollipop

```{r lollipop}

lollipop <- main_df %>%
  group_by(Variable) %>%
  summarise(number_of_data = n()) %>%
  ggplot(aes(x = reorder(Variable, -number_of_data),
             y = number_of_data,
             color = Variable,
             fill = Variable)) +
  geom_col(alpha = 1,
           width = .05,
           color = '#2f70a1',
           fill = '#2f70a1',
           show.legend = FALSE) +
  geom_point(alpha = 1,
             size = 15,
             color = '#2f70a1',
             show.legend = FALSE) +
  geom_point(alpha = .7,
             size = 25,
             color = '#2f70a1',
             show.legend = FALSE) +
  geom_point(alpha = .4,
             size = 35,
             color = '#2f70a1',
             show.legend = FALSE) +
  geom_point(alpha = .1,
             size = 45,
             color = '#2f70a1',
             show.legend = FALSE) +
  geom_text(aes(x = Variable,
                y = number_of_data,
                label = number_of_data), 
            size = 5, color = 'white') +
  scale_y_continuous(limits = c(0,35)) +
  theme_ranking +
  theme(axis.text.y = element_blank()) +
  xlab('Variable') +
  ylab('number of data') +
  labs(title = 'Lollipop',
       subtitle = 'Lollipop use to show bla bla bla.',
       caption = 'visualization by PanggahDPutra, 2022')

```

```{r lollipop print, echo=FALSE, out.width = "100%"}
lollipop
```

## Bump Chart

```{r bump chart}
bump <- df_for_bump %>%
  ggplot(aes(x = game,
             y = position,
             color = team)) +
  ggbump::geom_bump(size = 3,
                    smooth = 20,
                    show.legend = FALSE) +
  geom_point(size = 7) +
  geom_text(aes(label = position),
            size = 4,
            color = "white") +
  geom_text(data = df_for_bump %>% filter(game == min(game)),
            aes(x = game - .1,
                label = team),
            size = 5,
            hjust = 1) +
  geom_text(data = df_for_bump %>% filter(game == max(game)),
            aes(x = game + .1,
                label = team),
            size = 5,
            hjust = 0) +
  scale_color_manual(values = palette_ranking,
                     guide = 'none') +
  scale_y_reverse() +
  theme_ranking +
  xlab('Game-') +
  ylab('Ranking') +
  labs(title = 'Bump Chart',
       subtitle = 'Bump chart use to show bla bla bla.',
       caption = 'visualization by PanggahDPutra, 2022')

```

```{r bump print, echo=FALSE, out.width = "100%"}
bump
```

## ordered propt. symbol (not yet)
## dot strip plot (not yet)

***

# Distribution

## Histogram

```{r histogram, message=FALSE, warning=FALSE}

histogram <- main_df %>%
  ggplot(aes(x = value)) +
  geom_histogram(bins = 25,
                 alpha = .9,
                 fill = '#178f92',
                 color = '#175f5d') +
  scale_x_continuous(limits = c(0,10),
                     breaks = c(0,2,4,6,8,10)) +
  scale_y_continuous(limits = c(0,15),
                     breaks = c(0,5,10,15)) +
  theme_distr +
  ylab('number of data') +
  labs(title = 'Histogram',
       subtitle = 'Histogram use to show bla bla bla.',
       caption = 'visualization by PanggahDPutra, 2022')

```

```{r histogram print, echo=FALSE, out.width = "100%"}
histogram
```

## Dot Plot (Dumbbell Plot)

```{r dot plot}

dot_plot <- main_df %>%
  group_by(Variable) %>%
  summarise(min = min(value), max = max(value)) %>%
  ggplot(aes(x = min,
             xend = max,
             y = Variable,
             color = Variable,
             fill = Variable), ) +
  ggalt::geom_dumbbell(size =3,
                       size_x = 12,
                       size_xend = 12,
                       color = '#d8c29d',
                       colour_x = '#d8c29d',
                       colour_xend = '#d8c29d') +
  ggalt::geom_dumbbell(size = 3,
                       size_x = 9,
                       size_xend = 9,
                       color = '#d8c29d',
                       colour_x = '#4e3910',
                       colour_xend = '#175f5d') +
  geom_text(aes(x = min,
                y = Variable,
                label = round(min, 1)), 
            size = 3,
            color = 'white') +
  geom_text(aes(x = max,
                y = Variable,
                label = round(max, 1)), 
            size = 3,
            color = 'white') +
  scale_color_manual(values = palette_distr,
                     guide = 'none') +
  scale_fill_manual(values = palette_distr,
                    guide = 'none') +
  scale_x_continuous(limits = c(0,10),
                     breaks = c(0,2,4,6,8,10)) +
  theme_distr +
  xlab('min <<<value>>> max') +
  labs(title = 'Dot Plot (Dumbbell Plot)',
       subtitle = 'Dot Plot (Dumbbell Plot) use to show bla bla bla.',
       caption = 'visualization by PanggahDPutra, 2022')

```

```{r dot plot print, echo=FALSE, out.width = "100%"}
dot_plot
```

## Dot Strip Plot

```{r dot strip plot}

dot_strip_plot <- main_df %>%
  ggplot(aes(x = Variable,
             y = value,
             color = Variable,
             fill = Variable)) +
  ggdist::stat_dots(side = 'both') +
  scale_color_manual(values = palette_distr,
                     guide = 'none') +
  scale_fill_manual(values = palette_distr,
                    guide = 'none') +
  scale_y_continuous(limits = c(0,10),
                     breaks = c(0,2,4,6,8,10)) +
  theme_distr +
  labs(title = 'Dot Strip Plot',
       subtitle = 'Dot Strip Plot use to show bla bla bla.',
       caption = 'visualization by PanggahDPutra, 2022')

```

```{r dot strip plot print, echo=FALSE, out.width = "100%"}
dot_strip_plot
```

## Barcode Plot

```{r barcode plot}

barcode_plot <- main_df %>%
  ggplot(aes(x = Variable,
             y = value,
             color = Variable,
             fill = Variable)) +
  geom_point(shape = 95,
             size = 25,
             alpha = .7) +
  scale_color_manual(values = palette_distr,
                     guide = 'none') +
  scale_fill_manual(values = palette_distr,
                    guide = 'none') +
  scale_y_continuous(limits = c(0,10),
                     breaks = c(0,2,4,6,8,10)) +
  theme_distr +
  labs(title = 'Barcode Plot',
       subtitle = 'Barcode Plot use to show bla bla bla.',
       caption = 'visualization by PanggahDPutra, 2022')

```

```{r barcode plot print, echo=FALSE, out.width = "100%"}
barcode_plot
```

## Box Plot

```{r box plot}

box_plot <- main_df %>%
  ggplot(aes(x = Variable,
             y = value,
             color = Variable,
             fill = Variable)) +
  geom_boxplot(alpha = .7,
               size = .5,
               outlier.size = 2) +
  scale_color_manual(values = palette_distr,
                     guide = 'none') +
  scale_fill_manual(values = palette_distr,
                    guide = 'none') +
  scale_y_continuous(limits = c(0,10),
                     breaks = c(0,2,4,6,8,10)) +
  theme_distr +
  labs(title = 'Box Plot',
       subtitle = 'Box Plot use to show bla bla bla.',
       caption = 'visualization by PanggahDPutra, 2022')

```

```{r box plot print, echo=FALSE, out.width = "100%"}
box_plot
```

## violin plot

```{r violin plot}

violin_plot <- main_df %>%
  ggplot(aes(x = Variable,
             y = value,
             color = Variable,
             fill = Variable)) +
  geom_violin(alpha = .7,
              size = .5,
              bw = .25) +
  scale_color_manual(values = palette_distr,
                     guide = 'none') +
  scale_fill_manual(values = palette_distr,
                    guide = 'none') +
  scale_y_continuous(limits = c(0,10),
                     breaks = c(0,2,4,6,8,10)) +
  theme_distr +
  labs(title = 'Violin Plot',
       subtitle = 'Violin Plot use to show bla bla bla.',
       caption = 'visualization by PanggahDPutra, 2022')

```

```{r violin plot print, echo=FALSE, out.width = "100%"}
violin_plot
```

## Beeswarm

```{r beeswarm}

beeswarm_plot <- main_df %>%
  ggplot(aes(x = Variable,
             y = value,
             color = Variable,
             fill = Variable,
             size = value)) +
  ggbeeswarm::geom_beeswarm(alpha = .7,
                            cex = 3,
                            show.legend = FALSE) +
  scale_color_manual(values = palette_distr,
                     guide = 'none') +
  scale_fill_manual(values = palette_distr,
                    guide = 'none') +
  scale_y_continuous(limits = c(0,10),
                     breaks = c(0,2,4,6,8,10)) +
  theme_distr +
  labs(title = 'Beeswarm',
       subtitle = 'Beeswarm use to show bla bla bla.',
       caption = 'visualization by PanggahDPutra, 2022')

```

```{r beeswarm print, echo=FALSE, out.width = "100%"}
beeswarm_plot
```

## population pyramid (not yet)
## cumulative curve (not yet)
## frequency polygons (not yet)